// packages/solid/src/index.ts
import {
  createComponent,
  createContext,
  createSignal,
  onCleanup,
  Show,
  useContext,
  type Accessor,
  type JSX,
} from "solid-js";
import {
  createConsentStore,
  type Category,
  type ConsentExpr,
  type ConsentRecord,
  type ConsentRecordSource,
  type ConsentState,
  type ConsentStore,
  type Jurisdiction,
  type OpenCookiesConfig,
  type RepromptReason,
  type Route,
} from "@opencookies/core";

type Bound = {
  store: ConsentStore;
  state: Accessor<ConsentState>;
};

const Ctx = createContext<Bound | null>(null);

const NOT_PROVIDED_MESSAGE =
  "useConsent / useCategory / ConsentGate must be used inside <OpenCookiesProvider>";

function useBound(): Bound {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error(NOT_PROVIDED_MESSAGE);
  return ctx;
}

export type OpenCookiesProviderProps = (
  | { config: OpenCookiesConfig; store?: undefined }
  | { store: ConsentStore; config?: undefined }
) & { children?: JSX.Element };

export function OpenCookiesProvider(props: OpenCookiesProviderProps): JSX.Element {
  const store = props.store ?? createConsentStore(props.config!);
  const [state, setState] = createSignal<ConsentState>(store.getState(), { equals: false });
  const unsubscribe = store.subscribe(setState);
  onCleanup(unsubscribe);
  return createComponent(Ctx.Provider, {
    value: { store, state },
    get children() {
      return props.children;
    },
  });
}

export type UseConsentResult = {
  route: Accessor<Route>;
  categories: Accessor<Category[]>;
  decisions: Accessor<Record<string, boolean>>;
  jurisdiction: Accessor<Jurisdiction | null>;
  policyVersion: Accessor<string>;
  decidedAt: Accessor<string | null>;
  repromptReason: Accessor<RepromptReason | null>;
  has: (expr: ConsentExpr) => boolean;
  acceptAll: ConsentStore["acceptAll"];
  acceptNecessary: ConsentStore["acceptNecessary"];
  reject: ConsentStore["reject"];
  toggle: ConsentStore["toggle"];
  save: ConsentStore["save"];
  setRoute: ConsentStore["setRoute"];
  getConsentRecord: ConsentStore["getConsentRecord"];
  getPreviousRecord: ConsentStore["getPreviousRecord"];
};

export function useConsent(): UseConsentResult {
  const { store, state } = useBound();
  return {
    route: () => state().route,
    categories: () => state().categories,
    decisions: () => state().decisions,
    jurisdiction: () => state().jurisdiction,
    policyVersion: () => state().policyVersion,
    decidedAt: () => state().decidedAt,
    repromptReason: () => state().repromptReason,
    has: (expr) => {
      state();
      return store.has(expr);
    },
    acceptAll: (opts) => store.acceptAll(opts),
    acceptNecessary: (opts) => store.acceptNecessary(opts),
    reject: (opts) => store.reject(opts),
    toggle: (key, opts) => store.toggle(key, opts),
    save: (opts) => store.save(opts),
    setRoute: (route) => store.setRoute(route),
    getConsentRecord: () => {
      state();
      return store.getConsentRecord();
    },
    getPreviousRecord: () => {
      state();
      return store.getPreviousRecord();
    },
  };
}

export type UseCategoryResult = {
  granted: Accessor<boolean>;
  toggle: () => void;
};

export function useCategory(key: string): UseCategoryResult {
  const { store, state } = useBound();
  return {
    granted: () => state().decisions[key] === true,
    toggle: () => store.toggle(key),
  };
}

export type ConsentGateProps = {
  requires: ConsentExpr;
  fallback?: JSX.Element;
  children?: JSX.Element;
};

export function ConsentGate(props: ConsentGateProps): JSX.Element {
  const { store, state } = useBound();
  return createComponent(
    Show as (props: {
      when: boolean;
      keyed?: false;
      fallback?: JSX.Element;
      children?: JSX.Element;
    }) => JSX.Element,
    {
      get when() {
        state();
        return store.has(props.requires);
      },
      get fallback() {
        return props.fallback;
      },
      get children() {
        return props.children;
      },
    },
  );
}

export type {
  Category,
  ConsentExpr,
  ConsentRecord,
  ConsentRecordSource,
  ConsentState,
  ConsentStore,
  Jurisdiction,
  OpenCookiesConfig,
  RepromptReason,
  Route,
};

// packages/react/src/index.tsx
"use client";

import {
  createConsentStore,
  type Category,
  type ConsentExpr,
  type ConsentRecord,
  type ConsentRecordSource,
  type ConsentStore,
  type Jurisdiction,
  type OpenCookiesConfig,
  type RepromptReason,
  type Route,
} from "@opencookies/core";
import {
  createContext,
  useCallback,
  useContext,
  useState,
  useSyncExternalStore,
  type ReactNode,
} from "react";

export type OpenCookiesProviderProps =
  | { config: OpenCookiesConfig; store?: undefined; children: ReactNode }
  | { store: ConsentStore; config?: undefined; children: ReactNode };

const StoreContext = createContext<ConsentStore | null>(null);

export function OpenCookiesProvider(props: OpenCookiesProviderProps) {
  const [store] = useState<ConsentStore>(() => {
    if (props.store) return props.store;
    return createConsentStore(props.config);
  });
  return <StoreContext.Provider value={store}>{props.children}</StoreContext.Provider>;
}

function useStore(): ConsentStore {
  const store = useContext(StoreContext);
  if (!store) {
    throw new Error(
      "useConsent / useCategory / ConsentGate must be used inside <OpenCookiesProvider>",
    );
  }
  return store;
}

export type UseConsentResult = {
  route: Route;
  categories: Category[];
  decisions: Record<string, boolean>;
  jurisdiction: Jurisdiction | null;
  policyVersion: string;
  decidedAt: string | null;
  repromptReason: RepromptReason | null;
  acceptAll: ConsentStore["acceptAll"];
  acceptNecessary: ConsentStore["acceptNecessary"];
  reject: ConsentStore["reject"];
  toggle: ConsentStore["toggle"];
  save: ConsentStore["save"];
  setRoute: ConsentStore["setRoute"];
  has: ConsentStore["has"];
  getConsentRecord: ConsentStore["getConsentRecord"];
  getPreviousRecord: ConsentStore["getPreviousRecord"];
};

export function useConsent(): UseConsentResult {
  const store = useStore();
  const state = useSyncExternalStore(
    (cb) => store.subscribe(cb),
    () => store.getState(),
    () => store.getState(),
  );
  return {
    route: state.route,
    categories: state.categories,
    decisions: state.decisions,
    jurisdiction: state.jurisdiction,
    policyVersion: state.policyVersion,
    decidedAt: state.decidedAt,
    repromptReason: state.repromptReason,
    acceptAll: (opts) => store.acceptAll(opts),
    acceptNecessary: (opts) => store.acceptNecessary(opts),
    reject: (opts) => store.reject(opts),
    toggle: (key, opts) => store.toggle(key, opts),
    save: (opts) => store.save(opts),
    setRoute: (route) => store.setRoute(route),
    has: (expr) => store.has(expr),
    getConsentRecord: () => store.getConsentRecord(),
    getPreviousRecord: () => store.getPreviousRecord(),
  };
}

export type { ConsentRecord, ConsentRecordSource, RepromptReason };

export type UseCategoryResult = {
  granted: boolean;
  toggle: () => void;
};

export function useCategory(key: string): UseCategoryResult {
  const store = useStore();
  const granted = useSyncExternalStore(
    (cb) => store.subscribe(cb),
    () => store.getState().decisions[key] === true,
    () => store.getState().decisions[key] === true,
  );
  const toggle = useCallback(() => {
    store.toggle(key);
  }, [store, key]);
  return { granted, toggle };
}

export type ConsentGateProps = {
  requires: ConsentExpr;
  fallback?: ReactNode;
  children: ReactNode;
};

export function ConsentGate({ requires, fallback = null, children }: ConsentGateProps) {
  const store = useStore();
  const granted = useSyncExternalStore(
    (cb) => store.subscribe(cb),
    () => store.has(requires),
    () => store.has(requires),
  );
  return <>{granted ? children : fallback}</>;
}
